name: nf-core-m6APipe-1.0dev
channels:
  - bioconda
  - conda-forge
  - trent
  - defaults
  - r
dependencies:
  - openjdk=10.0.2=h14c3975_1015
  - r-base=3.5.1=he45234b_1005
  - python=2.7.15=h938d71a_1006
  - fastqc=0.11.8=1
  - fastp=0.19.7=hdbcaa40_0
  - bedtools=2.27.1=he860b03_3
  - ucsc-gtftogenepred=357=1
  - ucsc-fatotwobit=377=h199ee4e_1
  - hisat2=2.1.0=py27h6bb024c_3
  - bowtie2=2.2.5=py27h6bb024c_4
  - bwa=0.7.17=h84994c4_5
  - star=2.6.1b=0
  - tophat=2.1.1=py27_2
  - samtools=1.9=h43f6869_9
  - rseqc=2.6.4=py27hf8a1672_2
  - htseq=0.11.2=py27h637b7d7_1
  - cufflinks=2.2.1=py27_2
  - macs2=2.1.2=py27r351h14c3975_1
  - meme=5.0.2=py27pl526h96dd833_5
  - homer=4.9.1=pl526h2d50403_6
  - dos2unix=6.0.3=0
  - bioconductor-edger=3.24.1=r351hf484d3e_0
  - bioconductor-deseq2=1.22.1=r351hf484d3e_0
  - igvtools=2.3.93=0
  - bioconductor-exomepeak=2.16.0=r351_0
  - r-robustrankaggreg=1.1
  - perl=5.26.2=h14c3975_1002
  - r-ggplot2=3.1.1=r351h6115d3f_0
  - ucsc-genepredtobed=377=h199ee4e_1
  - scipy=1.2.1=py27he2b7bc3_0
  - deeptools=3.1.3=py27h14c3975_1