name: nf-core CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['19.04.0', '']
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Pull docker image
        run: |
          docker pull kingzhuky/meripseqpipe:dev
          docker tag kingzhuky/meripseqpipe:dev kingzhuky/meripseqpipe:dev
      - name: Run pipeline with test data
        run: |
          # Run the pipeline with the test profile
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --skip_peakCalling --skip_expression
          # Run, build reference genome with HISAT2
          nextflow run ${GITHUB_WORKSPACE} -profile test_mixed,docker --aligners hisat2 --skip_peakCalling --skip_expression -resume
          # Run, build reference genome with BWA
          nextflow run ${GITHUB_WORKSPACE} -profile test_mixed,docker --aligners bwa --skip_peakCalling --skip_expression -resume
          # Run, input date of the suffix of bam
          nextflow run ${GITHUB_WORKSPACE} -profile test_bam,docker -resume
          # Run, test PeakMerged mode 'metpeak' and Methylation Analysis mode 'MATK'
          nextflow run ${GITHUB_WORKSPACE} -profile test_bam,docker --peakMerged_mode metpeak --skip_expression --methylation_analysis_mode MATK -resume
          # Run, test one of PeakMerged mode 'bedtools' and Methylation Analysis mode 'DESeq2'
          nextflow run ${GITHUB_WORKSPACE} -profile test_bam,docker --peakMerged_mode macs2 --skip_expression --methylation_analysis_mode DESeq2 -resume
          # Run, test PeakCalling mode 'group' and Methylation Analysis mode 'QNB'
          nextflow run ${GITHUB_WORKSPACE} -profile test_bam,docker --peakCalling_mode group --skip_expression --methylation_analysis_mode QNB -resume
